#!/bin/bash
echo -e 'total 28\ndrwxr-xr-x 2 996 992 157 .\ndrwxr-xr-x 4 996 992 43 ..\n-rw-r--r-- 1 996 992 16 0-current_working_directory\n-rw-r--r-- 1 996 992 15 1-listit\n-rw-r--r-- 1 996 992 15 2-bring_me_home\n-rw-r--r-- 1 996 992 52 3-listfiles\n-rw-r--r-- 1 996 992 19 4-listmorefiles\n-rw-r--r-- 1 996 992 12 dummy_file\n-rw-r--r-- 1 996 992 27 README.md'
