#!/usr/bin/env bash
# Display unique users of running processes, with USER header padded with spaces

printf "USER   \n"
ps -eo user= | sort -u | while read -r user; do
    printf "%-7s\n" "$user"
done
