#!/usr/bin/env bash
# Infinite loop printing "To infinity and beyond" and trap SIGTERM to print "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
  echo "To infinity and beyond"
  sleep 2
done
